#include <stdio.h>

#include <windows.storage.h>

#include <Objbase.h>

EXTERN_C const IID IID___x_ABI_CWindows_CStorage_CStreams_CIBufferFactory = _uuidof(__x_ABI_CWindows_CStorage_CStreams_CIBufferFactory);

EXTERN_C const IID IID___x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory = _uuidof(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory);

EXTERN_C const IID IID___FIAsyncOperationCompletedHandler_1_UINT32 = _uuidof(__FIAsyncOperationCompletedHandler_1_UINT32);

EXTERN_C const IID IID___x_ABI_CWindows_CStorage_CStreams_CIOutputStream = _uuidof(__x_ABI_CWindows_CStorage_CStreams_CIOutputStream);

EXTERN_C const IID IID___x_ABI_CWindows_CStorage_CStreams_CIDataWriterFactory = _uuidof(__x_ABI_CWindows_CStorage_CStreams_CIDataWriterFactory);

EXTERN_C const IID IID___FIAsyncOperationCompletedHandler_1_boolean = _uuidof(__FIAsyncOperationCompletedHandler_1_boolean);

EXTERN_C const IID IID___x_ABI_CWindows_CSecurity_CCredentials_CIPasswordVault = _uuidof(__x_ABI_CWindows_CSecurity_CCredentials_CIPasswordVault);